### ISSUE TITLE
[DevOps] отказ от HTTP - редирект все на HTTPS

### ISSUE THREAD

**Issue by Mazian** [parserpro/fantlab_pub#35]
Поскольку HTTP протокол считается на сегодня устаревшим и для улучшение безопасности вместо него повсеместно предлагают исспользовать HTTPS.

fantlab.ru сейчас поддерживает оба протокола - HTTP и HTTPS для работы с сайтом.

В настройках хостов стоит указанием выбирать браузером версию HTTPS поэтому все пользователи уже и так и используют сайт -
![image](https://user-images.githubusercontent.com/5379752/77248590-a7b18f00-6c4b-11ea-90a2-0e8b04b553ad.png)

Логи говорят, что оставшиеся запросы по HTTP - это поисковые боты. Запросы от браузеров там уже не должно остаться.

Примеры других сайтов:
ru.wikipedia.org  
yandex.ru 
vk.com  
все заворачивают 80 на 443...

В связи с этим предлагается и у нас поставить принудительный редирект на HTTPS при заходе на HTTP. Будут ли возражения?

**Comment by g0ddest** [comment]
Мне кажется, что давно пора.
Как это реализовать? Клиентом через HSTS хидер, или же nginx-ом отдавать 301?

**Comment by Mazian** [comment]
HSTS давно стоит на сайте, поэтому я думаю все юзеры давно на SSL
> add_header Strict-Transport-Security "max-age=2592000";

с сегодняшнего дня добавил и полный редирект в конфиг хоста

> rewrite ^ https://$server_name$request_uri? permanent;

может просто какие-то скриптики сломать - я скорее об этом думаю. что не api-домен используют

**Comment by g0ddest** [comment]
Если просто добавь hsts, а не 301, то по идее оно не должно как-то повредить скриптам, работающим с api. Хотя многие http клиенты давно понимают что делать с 301.

**Comment by Mazian** [comment]
> Если просто добавь hsts, а не 301

ты как будто не слушаешь =)
HTSP то давно работает на сайте

**Comment by g0ddest** [comment]
```
http HEAD http://fantlab.ru
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Content-Length: 185
Content-Type: text/html
Date: Sun, 22 Mar 2020 13:34:11 GMT
Location: https://fantlab.ru/
Server: nginx/1.10.3
```
```
http HEAD https://fantlab.ru
HTTP/1.1 200 OK
Cache-Control: max-age=0
Cache-Control: no-cache
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html;charset=UTF-8
Date: Sun, 22 Mar 2020 13:35:22 GMT
Expires: Sun, 22 Mar 2020 13:35:22 GMT
FLid: 0
Server: nginx/1.10.3
```
А где заголовок `Strict-Transport-Security`?

**Comment by Mazian** [comment]
хм... не знаю.
в конфиге стоит 

```
server {
        listen       80;
        server_name  fantlab.ru www.fantlab.ru;

        expires 0;
        add_header Cache-Control no-cache;
        add_header Strict-Transport-Security "max-age=2592000; includeSubDomains" always;

        ...
}
```

**Comment by Mazian** [comment]
вот, перенес редирект под add_header и стал выдаваться

```
# http HEAD http://fantlab.ru
HTTP/1.1 200 OK
Cache-Control: max-age=0
Cache-Control: no-cache
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html;charset=UTF-8
Date: Sun, 22 Mar 2020 14:12:54 GMT
Expires: Sun, 22 Mar 2020 14:12:54 GMT
FLid: 0
Server: nginx/1.10.3
Strict-Transport-Security: max-age=2592000; includeSubDomains

```

**Comment by Mazian** [comment]
Ну вроде все ок. Трафик на http почти ноль стал (но не полный все ж, судя по метрике)
